substitutions:
  device_name: "shelly-1pm"
  name: "Shelly 1PM" 
  max_temp: "70.0"

esphome:
  name: ${device_name}
  comment: "Inverted relay, no power metering"

esp8266:
  board: esp01_1m
  restore_from_flash: true

logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  <<: !include ../network/wifi.yaml

captive_portal:

switch:
  - platform: gpio
    name: ${name}
    pin: 
      number: GPIO15
      inverted: true
    id: shelly_relay
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    device_class: signal_strength
    update_interval: 60s
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${name} temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - homeassistant.event:
              event: esphome.overheat
              data:
                title: "${name} has overheated."
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO00
      inverted: true
