ssid: "SSID"
password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
  ssid: "${name} Fallback AP"
  password: !secret ap_password

domain: ".lan"
